image: golang

before_script:
  - mkdir -p /home/gitlab-runner/go
  - export GOPATH=/home/gitlab-runner/go
  - export WORK_DIR=$GOPATH/src/github.com/SasukeBo/ftpviewer
  - export http_proxy=http://192.168.9.34:8001
  - export https_proxy=http://192.168.9.34:8001
  - mkdir -p $WORK_DIR
  - cp -r ./* $WORK_DIR
  - cd $WORK_DIR
  - pwd

job1:
  script:
    - cd intergration_test
    - go test
