image: golang

before_script:
  - export GOPATH=/home/gitlab-runner/go
  - export WORK_DIR=$GOPATH/src/github.com/SasukeBo/ftpviewer
  - export http_proxy=http://192.168.9.34:8001
  - export https_proxy=http://192.168.9.34:8001
  - mkdir -p $WORK_DIR
  - cp -r ./* $WORK_DIR
  - cd $WORK_DIR
  - GO111MODULE=on go get -u github.com/99designs/gqlgen
  - cd api/v1
  - gqlgen
  - cd admin
  - gqlgen

job1:
  script:
    - cd intergration_test
    - go test
