image: golang

before_script:
  - mkdir -p /home/gitlab-runner/go
  - export GOPATH=/home/gitlab-runner/go
  - export WORK_DIR=$GOPATH/src/github.com/SasukeBo/ftpviewer
  - mkdir -p $WORK_DIR
  - cp -r ./* $WORK_DIR
  - cd $WORK_DIR
  - ls -al
  - which go
  - whoami

job1:
  script:
    - cd intergration_test
    - go test