version: "3.7"
services:
  db:
    image: mysql:5.7
    networks:
      - ftpviewer
    ports:
      - "44766:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "ftpviewer"

  backend:
    image: sasukebo1229/ftpviewer-go:0.0.4
    depends_on:
      - db
    networks:
      - ftpviewer

  gateway:
    image: sasukebo1229/ftpviewer-nginx:0.0.2
    depends_on:
      - backend
    networks:
      - ftpviewer
    ports:
    - "80:80"

networks:
  ftpviewer:
