version: '3.7'
services:
  db:
    image: mysql:5.7
    networks:
      - ftpviewer
    ports:
      - '44766:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'ftpviewer'

  backend:
    image: ftpviewer-go
    depends_on:
      - db
    ports:
      - '44765:44761'
    networks:
      - ftpviewer

  # gateway:
  #   image: ftpviewer-nginx
  #   depends_on:
  #     - backend
  #   networks:
  #     - ftpviewer
  #   ports:
  #     - '80:80'

networks:
  ftpviewer:
