version: '3.3'
services:
  frontend:
    image: ftpviewer-vue
    networks:
      - ftpviewer

  ftp:
    image: fauria/vsftpd
    networks:
      - ftpviewer
    ports:
      - '20:20'
      - '21:21'
      - '21100-21110:21100-21110'
    environment:
      FTP_USER: 'ftpuploader'
      FTP_PASS: 'abc1234.'
      PASV_ADDRESS: '127.0.0.1'
      PASV_MIN_PORT: '21100'
      PASV_MAX_PORT: '21110'
    volumes:
      - "/home/sasukebo/ftproot:/home/vsftpd"

  db:
    image: mysql:5.7
    networks:
      - ftpviewer
    ports:
      - '44766:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'ftpviewer'

  backend:
    image: ftpviewer-go
    depends_on:
      - db
    ports:
      - '44765:44761'
    networks:
      - ftpviewer

  gateway:
    image: ftpviewer-nginx
    depends_on:
      - backend
    networks:
      - ftpviewer
    ports:
      - '80:80'

networks:
  ftpviewer:
