version: '3.3'
services:
  frontend:
    image: ftpviewer_frontend
    networks:
      - ftpviewer
    environment:
      PORT: '44761'
    volumes:
      - "/path/to/your/yarn/build/dist:/server"

  ftp:
    image: fauria/vsftpd
    networks:
      - ftpviewer
    ports:
      - '20:20'
      - '21:21'
      - '21100-21110:21100-21110'
    environment:
      FTP_USER: 'ftpuploader'
      FTP_PASS: 'abc1234.'
      PASV_ADDRESS: '127.0.0.1'
      PASV_MIN_PORT: '21100'
      PASV_MAX_PORT: '21110'
    volumes:
      - "/home/sasukebo/ftproot:/home/vsftpd" # change to your local ftpservice data root directory on your host machine

  db:
    image: mysql:5.7
    networks:
      - ftpviewer
    ports:
      - '44766:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'ftpviewer'

  backend:
    image: ftpviewer_backend
    depends_on:
      - db
    ports:
      - '44765:44761'
    networks:
      - ftpviewer
    environment:
      DB_DNS: 'root:123456@tcp(db:3306)/ftpviewer?charset=utf8mb4&parseTime=True&loc=Local'

  gateway:
    image: ftpviewer_gateway
    depends_on:
      - backend
    networks:
      - ftpviewer
    ports:
      - '80:80'

networks:
  ftpviewer:
