// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID      int    `json:"id"`
	Account string `json:"account"`
	IsAdmin bool   `json:"isAdmin"`
	UUID    string `json:"uuid"`
}
